# Generated by Django 4.2.28 on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_securityevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('LOGIN_SUCCESS', 'Login Success'),
                    ('LOGIN_FAILURE', 'Login Failure'),
                    ('LOGOUT', 'Logout'),
                    ('REGISTRATION', 'Registration'),
                    ('PASSWORD_CHANGE', 'Password Change'),
                    ('PROFILE_UPDATE', 'Profile Update'),
                    ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'),
                    ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'),
                    ('VERIFICATION_EMAIL_SENT', 'Verification Email Sent'),
                    ('EMAIL_VERIFIED', 'Email Verified'),
                    ('CAPTCHA_REQUIRED', 'CAPTCHA Required'),
                    ('CAPTCHA_FAILED', 'CAPTCHA Failed'),
                    ('CAPTCHA_PASSED', 'CAPTCHA Passed'),
                    ('ACCOUNT_LOCKED', 'Account Locked'),
                    (
                        'LOGIN_BLOCKED_UNVERIFIED',
                        'Login Blocked - Email Not Verified',
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
